apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice-deploy
  labels:
    app: userservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userservice
  template:
    metadata:
      labels:
        app: userservice
    spec:
      containers:
      - name: bloguserservice
        image: sonusathyadas/bloguserservice:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: Jwt__Key
          value: SomeSampleKeyWhichisLarge
        - name: Jwt__Issuer
          value: http://userservice/      